# NextChat Kubernetes Development Kustomization Configuration
# Development environment overrides

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: nextchat-development
  labels:
    app: nextchat
    environment: development

namespace: nextchat-dev

resources:
- ../base

commonLabels:
  app: nextchat
  version: v1.0.0
  environment: development
  managed-by: kustomize

commonAnnotations:
  deployment.kubernetes.io/revision: "1"
  kubernetes.io/change-cause: "Development deployment"

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: nextchat
  spec:
    replicas: 1
    template:
      spec:
        containers:
        - name: nextchat
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          env:
          - name: NODE_ENV
            value: "development"
          - name: DEPLOYMENT_ENVIRONMENT
            value: "development"
          - name: LOG_LEVEL
            value: "debug"
          - name: METRICS_ENABLED
            value: "true"
          - name: FEATURE_DEBUG_MODE
            value: "true"
          - name: RATE_LIMIT_MAX
            value: "100"
          - name: DB_POOL_MAX
            value: "5"
          - name: REDIS_MAX_RETRIES
            value: "3"
          - name: AI_AGENT_MAX_CONCURRENT
            value: "10"
          - name: PLUGIN_VALIDATION_ENABLED
            value: "false"
          - name: PLUGIN_SANDBOX_ENABLED
            value: "false"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
- |-
  apiVersion: autoscaling/v2
  kind: HorizontalPodAutoscaler
  metadata:
    name: nextchat-hpa
  spec:
    minReplicas: 1
    maxReplicas: 3
    metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
        - type: Percent
          value: 50
          periodSeconds: 60
        - type: Pods
          value: 1
          periodSeconds: 60
        selectPolicy: Min
      scaleUp:
        stabilizationWindowSeconds: 60
        policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 2
          periodSeconds: 60
        selectPolicy: Max
- |-
  apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    name: nextchat-pdb
  spec:
    minAvailable: 0
- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: nextchat-config
  data:
    NODE_ENV: "development"
    LOG_LEVEL: "debug"
    API_TIMEOUT: "30000"
    MAX_REQUEST_SIZE: "10mb"
    DB_POOL_MIN: "1"
    DB_POOL_MAX: "5"
    DB_TIMEOUT: "30000"
    REDIS_TIMEOUT: "5000"
    REDIS_RETRY_DELAY: "100"
    REDIS_MAX_RETRIES: "3"
    CORS_ORIGIN: "*"
    RATE_LIMIT_WINDOW: "900000"
    RATE_LIMIT_MAX: "100"
    METRICS_ENABLED: "true"
    METRICS_PORT: "9090"
    HEALTH_CHECK_INTERVAL: "30000"
    FEATURE_PLUGINS_ENABLED: "true"
    FEATURE_ANALYTICS_ENABLED: "false"
    FEATURE_DEBUG_MODE: "true"
    PLUGIN_MARKETPLACE_URL: "https://dev-plugins.nextchat.com"
    PLUGIN_VALIDATION_ENABLED: "false"
    PLUGIN_SANDBOX_ENABLED: "false"
    AI_AGENT_TIMEOUT: "60000"
    AI_AGENT_MAX_CONCURRENT: "10"
    AI_AGENT_RETRY_ATTEMPTS: "3"
    DEPLOYMENT_VERSION: "v1.0.0"
    DEPLOYMENT_ENVIRONMENT: "development"
    DEPLOYMENT_REGION: "us-west-2"
