# NextChat Security Policies
# Kubernetes security policies and constraints

apiVersion: v1
kind: Namespace
metadata:
  name: nextchat
  labels:
    name: nextchat
    security: enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nextchat-service-account
  namespace: nextchat
automountServiceAccountToken: false
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: nextchat-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nextchat-psp-user
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs: ['use']
  resourceNames:
  - nextchat-psp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nextchat-psp-binding
  namespace: nextchat
roleRef:
  kind: ClusterRole
  name: nextchat-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: nextchat-service-account
  namespace: nextchat
